package cn.kspshare.domain;

import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ksp_member
 */
public class KspMember {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.oid")
    private Long oid;

    /**
     * Database Column Remarks:
     *   账号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.username")
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.password")
    private String password;

    /**
     * Database Column Remarks:
     *   昵称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.nickname")
    private String nickname;

    /**
     * Database Column Remarks:
     *   唯一邮箱
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.email")
    private String email;

    /**
     * Database Column Remarks:
     *   邮箱验证： 0未验证 1已验证 ， 默认0
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.enabled")
    private Byte enabled;

    /**
     * Database Column Remarks:
     *   用户状态：1允许登录 0禁止登录 ， 默认1
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.user_status")
    private Byte userStatus;

    /**
     * Database Column Remarks:
     *   头像url路径
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.avatar")
    private String avatar;

    /**
     * Database Column Remarks:
     *   0保密 1男 2女，默认0
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.gender")
    private Byte gender;

    /**
     * Database Column Remarks:
     *   简单地址信息
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.location")
    private String location;

    /**
     * Database Column Remarks:
     *   兴趣爱好
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.hobbies")
    private String hobbies;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_time")
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建人ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_user")
    private Long createUser;

    /**
     * Database Column Remarks:
     *   身份权限
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.roles")
    private String roles;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.oid")
    public Long getOid() {
        return oid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.oid")
    public void setOid(Long oid) {
        this.oid = oid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.username")
    public String getUsername() {
        return username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.username")
    public void setUsername(String username) {
        this.username = username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.password")
    public String getPassword() {
        return password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.password")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.nickname")
    public String getNickname() {
        return nickname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.nickname")
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.email")
    public String getEmail() {
        return email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.email")
    public void setEmail(String email) {
        this.email = email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.enabled")
    public Byte getEnabled() {
        return enabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.enabled")
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.user_status")
    public Byte getUserStatus() {
        return userStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.user_status")
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.avatar")
    public String getAvatar() {
        return avatar;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.avatar")
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.gender")
    public Byte getGender() {
        return gender;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.gender")
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.location")
    public String getLocation() {
        return location;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.location")
    public void setLocation(String location) {
        this.location = location;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.hobbies")
    public String getHobbies() {
        return hobbies;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.hobbies")
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_time")
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_time")
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_user")
    public Long getCreateUser() {
        return createUser;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.create_user")
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.roles")
    public String getRoles() {
        return roles;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ksp_member.roles")
    public void setRoles(String roles) {
        this.roles = roles;
    }
}