package cn.kspshare.domain;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test_user
 */
public class TestUser {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.tid")
    private Long tid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.user_name")
    private String userName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.age")
    private Integer age;

    /**
     * Database Column Remarks:
     *   1
     *               2
     *               3
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.grade_id")
    private Long gradeId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.tid")
    public Long getTid() {
        return tid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.tid")
    public void setTid(Long tid) {
        this.tid = tid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.user_name")
    public String getUserName() {
        return userName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.user_name")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.age")
    public Integer getAge() {
        return age;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.age")
    public void setAge(Integer age) {
        this.age = age;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.grade_id")
    public Long getGradeId() {
        return gradeId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_user.grade_id")
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }
}