package cn.kspshare.domain;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test_grade
 */
public class TestGrade {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.tid")
    private Long tid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_name")
    private String gradeName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_code")
    private String gradeCode;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.level")
    private Integer level;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.tid")
    public Long getTid() {
        return tid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.tid")
    public void setTid(Long tid) {
        this.tid = tid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_name")
    public String getGradeName() {
        return gradeName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_name")
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_code")
    public String getGradeCode() {
        return gradeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.grade_code")
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.level")
    public Integer getLevel() {
        return level;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: test_grade.level")
    public void setLevel(Integer level) {
        this.level = level;
    }
}